Algoritmo "MEDIA"
Var
// Seção de Declarações das variáveis 
n1,n2,n3,media: real
nome: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Qual seu nome?")
leia(nome)
escreval("Qual sua 1ºnota?")
leia(n1)
escreval("Qual sua 2ºnota?")
leia(n2)
escreval("Qual sua 3ºnota?")
leia(n3)
escreval("Qual sua 2ºnota?")
media <- (n1 + n2 + n3) / 3

escreval("A média de ", nome, " é ", media)
Fimalgoritmo