Algoritmo "lucro"

Var
// Seção de Declarações das variáveis 
j, f, m, media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Qual o lucro de Janeiro?")
leia(j)
escreval("Qual o lucro de Fevereiro?")
leia(f)
escreval("Qual o lucro de Março?")
leia(m)

media <- (j + f + m) / 3

escreval("A média de lucro é de ",media, " Reais")

Fimalgoritmo